[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
on_chain_voting = "4c1xHGDjPz6DMzDRvTedYJzUc4yAdKbsYRSFNxbQrSSr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
