[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "3cTUttpK3K84oG9Ax5WJDiCjPqqdz3KN9qWbXa7mRYbs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
